
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Documents", targetNamespace = "http://webServices/", wsdlLocation = "http://localhost:5555/Laborator8-1.0-SNAPSHOT/Documents?wsdl")
public class Documents
    extends Service
{

    private final static URL DOCUMENTS_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTS_EXCEPTION;
    private final static QName DOCUMENTS_QNAME = new QName("http://webServices/", "Documents");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5555/Laborator8-1.0-SNAPSHOT/Documents?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCUMENTS_WSDL_LOCATION = url;
        DOCUMENTS_EXCEPTION = e;
    }

    public Documents() {
        super(__getWsdlLocation(), DOCUMENTS_QNAME);
    }

    public Documents(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTS_QNAME, features);
    }

    public Documents(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTS_QNAME);
    }

    public Documents(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTS_QNAME, features);
    }

    public Documents(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Documents(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetDocumentsService
     */
    @WebEndpoint(name = "getDocumentsServicePort")
    public GetDocumentsService getGetDocumentsServicePort() {
        return super.getPort(new QName("http://webServices/", "getDocumentsServicePort"), GetDocumentsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDocumentsService
     */
    @WebEndpoint(name = "getDocumentsServicePort")
    public GetDocumentsService getGetDocumentsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "getDocumentsServicePort"), GetDocumentsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTS_EXCEPTION!= null) {
            throw DOCUMENTS_EXCEPTION;
        }
        return DOCUMENTS_WSDL_LOCATION;
    }

}
